Update examples to use config instead of configuration
pulumi/examples pull request #1305
Opened 2022-11-11 21:10 UTC by aq17

Fixes #1304

2022-11-12 00:21 UTC, iwahbe requested changes

2022-11-12 00:21 UTC, iwahbe commented on kubernetes-yaml/Pulumi.yaml
>      type: String
`String` is not a valid type for `config`. It needs to be `string`.

2022-11-12 00:21 UTC, iwahbe commented on azure-yaml-container-apps/Pulumi.yaml
> +      config:
Regexp based replace would benefit from `^configuration:` to prevent this kind of thing.

2022-11-14 22:52 UTC, iwahbe commented
I don't think that https://github.com/pulumi/examples/pull/1305/commits/c71b9f76176a0bb472f75c9a509cd8e474443dd1 made the changes you wanted it to.

2022-11-14 22:55 UTC, aq17 commented
> c71b9f7

My bad I've been focusing on OR this morning, still need to fix this

2022-11-14 23:43 UTC, iwahbe approved these changes

2022-11-17 03:29 UTC, merged