Output-ify JSON use in CreateRoleStack
pulumi/examples pull request #1325
Opened 2022-12-16 16:29 UTC by Frassle

2023-02-06 14:12 UTC, justinvp approved these changes

2023-03-22 17:49 UTC, dixler approved these changes
Anything keeping us from merging this?

2025-01-13 21:07 UTC, rshade requested changes
It looks like with one change it will build

2025-01-13 21:07 UTC, rshade commented on aws-cs-assume-role/create-role/CreateRoleStack.cs
> +        var tempPolicy = Output.JsonSerialize<AssumeRolePolicyArgs>(policyArgs);
```suggestion
         var tempPolicy = Output.Create(policyArgs).Apply(args => JsonSerializer.Serialize(args));
```

2025-03-20 14:32 UTC, rshade commented
```
 pulumi up --yes
Previewing update (dev)

View in Browser (Ctrl+O): https://app.pulumi.com/team-ce/aws-cs-create-role/dev/previews/4c7c76de-6ec7-498f-a496-2ffc448836f8

     Type                      Name                        Plan
     pulumi:pulumi:Stack       aws-cs-create-role-dev
 +   └─ aws:iam:Role           allow-s3-management         create
 +      └─ aws:iam:RolePolicy  allow-s3-management-policy  create

Outputs:
  + accessKeyId    : "XXXXXXXXXXXXXXXXXXXXX"
  + roleArn        : output<string>
  + secretAccessKey: [secret]

Resources:
    + 2 to create
    3 unchanged

Updating (dev)

View in Browser (Ctrl+O): https://app.pulumi.com/team-ce/aws-cs-create-role/dev/updates/3

     Type                      Name                        Status
     pulumi:pulumi:Stack       aws-cs-create-role-dev
 +   └─ aws:iam:Role           allow-s3-management         created (1s)
 +      └─ aws:iam:RolePolicy  allow-s3-management-policy  created (0.43s)

Outputs:
  + accessKeyId    : "XXXXXXXXXXXXXXXXXXXX"
  + roleArn        : "arn:aws:iam::XXXXXXXXX:role/allow-s3-management-e731b2c"
  + secretAccessKey: [secret]

Resources:
    + 2 created
    3 unchanged

Duration: 7s
```

2025-03-20 19:21 UTC, mjeffryes approved these changes

2025-03-20 19:21 UTC, merged