Add AWS hub and spoke example
pulumi/examples pull request #1406
Opened 2023-03-30 19:26 UTC by jkodroff

2023-04-04 15:15 UTC, jkodroff commented
@cnunciato Would be good to merge now if possible so I can ensure the link is correct for the blog post if you're ok with it.

2023-04-04 20:03 UTC, scottslowe requested changes
I haven't run the example yet (will do so shortly), but I am curious about the change to `gcp-ts-cloudrun/package.json`?

2023-04-04 20:03 UTC, scottslowe commented on gcp-ts-cloudrun/package.json
> +        "@pulumi/awsx": "^0.40.0",
Is there a reason for this seemingly-unrelated change? It also seems like a change we would not want to make.

2023-04-04 20:11 UTC, scottslowe commented
@jkodroff Also, we need to be sure we are providing more complete README's for examples like this. Would you mind making your `README.md` conform to what's outlined in `CONTRIBUTING.md`, please? Sorry, don't mean to be difficult, but at some point we have to start enforcing that proper README's are included for every example. Thanks!

2023-04-04 21:14 UTC, scottslowe commented
@jkodroff The updated README looks great, thanks! The only outstanding question for me was the weird change to the `gcp-ts-cloudrun` example, what's up with that?

2023-04-05 14:02 UTC, scottslowe approved these changes
Approved, thank you!

2023-04-05 14:52 UTC, merged