Update examples to AWS v6
pulumi/examples pull request #1471
Opened 2023-08-02 22:03 UTC by mnlumi

2023-08-02 22:03 UTC, mnlumi commented
Setting to alpha release for testing.

2023-08-02 22:06 UTC, mnlumi commented
FYI @cnunciato I've got this set to the alpha release for testing right now. They will be updated to v6 once the actual release is cut.

2023-08-07 21:34 UTC, t0yv0 commented on testing-unit-go/main_test.go
> +			userData := all[1].(string)
Breaking change somewhere?

2023-08-21 15:23 UTC, t0yv0 commented
A new [v6.0.0-alpha.1](https://github.com/pulumi/pulumi-aws/releases/tag/untagged-72a25b9a4bca1aa05af3) alpha is out, let me see if I can update quickly.

2023-08-29 20:31 UTC, mnlumi commented
Equinix failures are unrelated to AWS 6.0. The test on `TestAccAwsPyEc2Provisioner` is also unrelated and is being handled separately via https://github.com/pulumi/examples/issues/1491 and https://github.com/pulumi/examples/pull/1492.

2023-08-30 03:13 UTC, iwahbe approved these changes

2023-08-30 12:01 UTC, thomas11 requested changes
I checked out the PR branch and ran some searches and the following seem to be missing:

```
> rg 'aws.+<6.0'
aws-py-hub-and-spoke-network/requirements.txt
2:pulumi_aws>=5.0.0,<6.0.0

> rg 'pulumi-aws/sdk/v5'
aws-go-fargate/go.mod
6:	github.com/pulumi/pulumi-aws/sdk/v5 v5.41.0
47:	github.com/pulumi/pulumi-aws/sdk/v5 v5.16.2 // indirect

aws-go-fargate/main.go
8:	"github.com/pulumi/pulumi-aws/sdk/v5/go/aws/ec2"
9:	"github.com/pulumi/pulumi-aws/sdk/v5/go/aws/ecr"
10:	"github.com/pulumi/pulumi-aws/sdk/v5/go/aws/ecs"
11:	elb "github.com/pulumi/pulumi-aws/sdk/v5/go/aws/elasticloadbalancingv2"
12:	"github.com/pulumi/pulumi-aws/sdk/v5/go/aws/iam"

aws-go-fargate/go.sum
[...]
```

2023-08-30 19:06 UTC, mnlumi commented
Ive intentionally excluded updates to examples that also use awsx. I will update those after the next awsx release that takes in aws 6.0.

@thomas11 The programs you mentioned both use awsx.
- aws-py-hub-and-spoke-network
- aws-go-fargate

2023-08-31 06:04 UTC, thomas11 approved these changes

2023-08-31 14:33 UTC, merged