Adding TypeScript Example for Azure OIDC with ESC
pulumi/examples pull request #1529
Opened 2023-11-17 15:48 UTC by toriancrane

Adding TypeScript Example for Azure OIDC with ESC

2023-11-17 20:24 UTC, scottslowe requested changes
A couple minor changes, plus it looks like there are some linting failures that need to be addressed.

2023-11-17 20:24 UTC, scottslowe commented on azure-ts-oidc-provider-pulumi/Pulumi.yaml
> +name: azure-ts
```suggestion
name: azure-ts-oidc-provider-pulumi
```

2023-11-17 20:24 UTC, scottslowe commented on azure-ts-oidc-provider-pulumi/Pulumi.yaml
> +description: A minimal Azure Native TypeScript Pulumi program
```suggestion
description: An Azure Native TypeScript Pulumi program to setup OIDC
```

2023-11-17 21:10 UTC, desteves commented on azure-ts-oidc-provider-pulumi/README.md
> +cd examples/azure-ts-oidc-provider-pulumi-cloud
remove `-cloud`

2023-11-17 21:11 UTC, desteves commented on azure-ts-oidc-provider-pulumi/README.md
> +Start by [creating a new Pulumi ESC environment](https://www.pulumi.com/docs/pulumi-cloud/esc/get-started/#create-an-environment). Then, copy the template definition from the output in the CLI and pa
Break this into 3 substeps

2023-11-17 21:13 UTC, desteves commented on azure-ts-oidc-provider-pulumi/package.json
> +        "@types/node": "^16.18.61",
Can we do node 18+  as 16 EOL'd

2023-11-17 21:13 UTC, desteves reviewed
minor suggestions

2023-11-27 14:26 UTC, toriancrane commented on azure-ts-oidc-provider-pulumi/README.md
> +cd examples/azure-ts-oidc-provider-pulumi-cloud
That is the actual name of the folder.

2023-11-28 16:30 UTC, desteves approved these changes

2023-11-29 19:41 UTC, scottslowe requested changes
One minor change needed, otherwise looks good

2023-11-30 18:17 UTC, merged