Fix AWS OIDC TS example
pulumi/examples pull request #1719
Opened 2024-11-01 19:08 UTC by jkodroff

It's not possible to have a single stack which handles both the use case of creating a new OIDC provider and also adding an audience if none exists. This change removes the conditional creation of an OIDC provider and assumes none exists.

2024-11-02 08:00 UTC, pierskarsenbarg approved these changes

2024-11-02 12:28 UTC, pierskarsenbarg requested changes
Couple of linting errors to fix

2024-11-04 19:28 UTC, pierskarsenbarg approved these changes

2024-11-05 17:13 UTC, thoward commented
Looks good. Thanks for this! Would love to see an update to the README that explains this limitation.

2024-11-05 17:23 UTC, merged

2024-11-05 17:23 UTC, thoward commented
Merging for @jkodroff per request.