Add Integration test in python example with docs
pulumi/examples pull request #881
Opened 2021-01-23 00:09 UTC by wuqunfei

2021-02-03 19:24 UTC, komalali commented on testing-integration-py/README.md
> + - In the end, don't forget destroy the stack.
```suggestion
 - Create a stack and export the desired outputs.
 - Validate any output values you defined in advance.
 - In the end, don't forget to destroy the stack. 
```

2021-02-03 19:27 UTC, komalali commented on testing-integration-py/test_s3_it.py
> +        cls.stack.destroy(on_output=print)
You might want to remove the stack completely at the end.

```suggestion
        cls.stack.destroy(on_output=print)
        cls.stack.workspace.remove_stack(cls.STACK_NAME)
```

2021-02-03 19:29 UTC, komalali commented on testing-integration-py/README.md
> +        cls.outputs = cls.stack.outputs()
Might be helpful to specify that an `up` is necessary before pulling outputs.
```suggestion
		cls.stack.up(output=print)
        cls.outputs = cls.stack.outputs() 
```

2021-02-03 19:29 UTC, komalali commented on testing-integration-py/README.md
> +        cls.stack.destroy(on_output=print)
You might want to remove the stack completely at the end.

```suggestion
        cls.stack.destroy(on_output=print)
        cls.stack.workspace.remove_stack(cls.STACK_NAME)  
```

2021-02-03 19:36 UTC, komalali requested changes
Whoops, accidentally hit approve. Once you update the changes I recommended I'd be happy to approve it.

2021-02-05 20:04 UTC, wuqunfei reviewed
thanks, you made it perfect.

2021-02-05 20:09 UTC, komalali commented
/run-example-tests

2021-02-06 00:18 UTC, komalali approved these changes

2021-02-06 00:19 UTC, merged